openapi: 3.0.4
info:
  title: Emoji Decorator
  description: Emoji Decorator is a simple tool for decorating text with emojis. It returns the text decorated with emojis.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/emojidecorator:
    post:
      summary: Decorate Text with Emojis
      description: Emoji Decorator is a simple tool for decorating text with emojis. It returns the text decorated with emojis.
      operationId: emojidecorator
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  decorated: "I am so excited \U0001F4EC to go \U0001F91B\U0001F3FE to the lake \U0001F64F\U0001F3FC\U0001F1FA\U0001F1F8 and swim \U0001F459"
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text you want decorated with emojis
                  example: I am so excited to go to the lake and swim
              required:
              - text
              example:
                text: I am so excited to go to the lake and swim
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
